### ISSUE TITLE
Question not and issue.

### ISSUE THREAD

**Issue by Addgod** [kodeine/laravel-acl#38]
This is more a question then a issue.

When implementing the acl. How would you go about managing this. If I make a admin page that manages the permissions. How would the database know witch permissions have been implemented into the routes file, and for that matter in the code? 

Also if I make use of Roles in routes, then how are these roles translated into actual permission sets in the database? 

In my mind if I implement either a role or a user permission in the routes file or anywhere else, this should some how be available to me in the interface, so that it is not necessary to implement the roles "by memory". Would this some how be possible?

**Comment by Rtransat** [comment]
You looking an panel admin ? Something like that ? https://github.com/Rtransat/laravel-entrust-role-permission-panel#screenshots

**Comment by kodeine** [comment]
@Rtransat 
I assume you're making one using laravel-acl. :+1:

**Comment by Addgod** [comment]
It is not so much the actual implementation of the admin panel that is my question, more the usage of it. 

Example.
I in the code add a is('moderator') in my routes files. That translates into a new role. In my mind, then this role should automatically be added into a usable role in the database, or in the admin panel, so I can start assigning users to this role. 

But as far as I can figure out, with how it works now, I have to assign the role manually in both the development environment and the production environment. This is in my min a potential problem, or a in a lager scale setup. These are things that the system should be able to do automatically, depending on the code, and what is being used.

**Comment by Rtransat** [comment]
@kodeine Yes ;). But it's more complex than entrust because I need to read slug field for each permissions and display like that:

|        | Admin | Editor | User |
|--------|-------|--------|------|
| **Role**   |       |        |      |
| create |       |        |      |
| view   |       |        |      |
| edit   |       |        |      |
| delete |       |        |      |
| **User**   |       |        |      |
| create |       |        |      |

And your middleware is good :). And for check route automatically I need to create a middleware that which automatically all the route:

```php
Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'authorize']], function() {});
```

If you want integrate that in your package I am not against :p

**Comment by Rtransat** [comment]
@Addgod If I understand what you want, you need to create an admin to assign permission to role.

roles and permissions resources for example. And with checkboxes (relationships between role and permission) you choose permissions for a role.

I don't know if I understand what you want, sorry for my english :/

**Comment by Addgod** [comment]
Well what I really want is that the code it self is what generates what permissions and roles are available. So that as much human error is kinda eliminated.

**Comment by Addgod** [comment]
@kodeine Do you have a live example of how you have implemented this in the backend, because I cannot quite wrap my head around it to be honest.

**Comment by kodeine** [comment]
@Addgod as far i understood, once you add a role/permission from panel, you need that to reflect in routes file automatically so you dont have to manually edit routes.php right?

@Rtransat yes i would be very interested in integrating your panel into acl but with seperation so if people need it without panel they can still use acl without it :)

**Comment by Addgod** [comment]
@kodeine Actually I was thinking the other way around. When ever you use a permission is your routes fie, or in the code directly it would update either the role database, or the permission data base, with that give object.

But in general I am having a hard time wrapping my head around implementing it the way it was ment to be. Like how is the whole permission inherentense thing supposed to be implemented in an admin panel.

**Comment by Addgod** [comment]
Has anyone actually created an admin panel, that uses this acl implementation?

**Comment by kbhatt2006** [comment]
@kodeine I am really happy with what is happening on this repo. I propose admin panel with your laravel-acl implementation  ! since you want seperate admin-panel with acl, lets create new repo !! I am eager to contribute.
cc @Rtransat

**Comment by Addgod** [comment]
I would love to see an implementation of this in an admin panel somewhere, since I still have not wrapped my head completely around this implementation.

**Comment by kodeine** [comment]
@Rtransat hows the panel coming along with this acl? Mind sharing the repo so we can jump on what you've done so far?

@kbhatt2006  i will definitely be working on the admin panel of the acl. As soon i get time from other work ill jump onto it. 

@Addgod when you code your website/panel you already know your routes, since they don't change on fly and you have to write your routes to make your site work right? So you don't need an ability to add permissions or roles to the routes on fly. You already have roles/permissions assigned on your routes so what you can do is change the permissions and roles of users so they dont have access to certain permissions and roles. I hope i was able to explain, feel free to write if you need more detail :)

**Comment by Rtransat** [comment]
@kodeine For now I have no time :(

**Comment by Addgod** [comment]
@kodeine I agree, that way it should be possible, but where would you actually keep the permissions that it used, would they be hardcoded into a form?

**Comment by kodeine** [comment]
you can get the permissions from db, all permissions and roles are in db.

**Comment by RomainLanz** [comment]
Closed due to inactivity.

**Comment by elrco** [comment]
Hi there, if you think this topic can be re-opened, well yo can count on me to build a basic admin panel! So please let me know if there is any interest :)

**Comment by teslaji** [comment]
@elrco Count me In ! , I am up for contributing for admin panel..

**Comment by elrco** [comment]
@teslaji very well, can you guide the route? I'm new to kodeine's ACL package. Can you split the work into parts to start?! It seem's writing the panel for kodeine is a bit harder that entrust.

**Comment by kodeine** [comment]
@Addgod @Rtransat
We will be building acl panel, if you guys want to volunteer, please [chime in](https://github.com/kodeine/laravel-acl-panel)
