### ISSUE TITLE
Blade template

### ISSUE THREAD

**Issue by avlastenok** [kodeine/laravel-acl#63]
using 
@role('artist')
        test
@endrole

simply outputs the blade stuff as if it were text, i'm in Laravel 5.1 I have not tested in 5.0.x

**Comment by RomainLanz** [comment]
Hi,

Have you try with the normal syntax?

```
@if(Auth::check() && Auth::user()->is('admin|moderator'))
```

**Comment by avlastenok** [comment]
Of cause the normal check works which is why the topic was blade.

**Comment by RomainLanz** [comment]
Which version did you use?

Blade template has been added only on master branch, it'll be backported on the week.

**Comment by fishmad** [comment]
I have same thing:

"laravel/framework": "5.0.33",
"kodeine/laravel-acl": "~1.0@dev"

**Comment by RomainLanz** [comment]
You should use master branch.

`"kodeine/laravel-acl": "dev-master"`

**Comment by curtsheller** [comment]
Using "dev-master" returns this from composer diagnose -vvvv:

`````
Checking composer.json: FAIL
require.kodeine/laravel-acl : unbound version constraints (dev-master) should be avoided
`````

Which composer docs (https://getcomposer.org/doc/faqs/why-are-unbound-version-constraints-a-bad-idea.md) suggest is a bad idea.

-----
Why are unbound version constraints a bad idea?#

A version constraint without an upper bound such as *, >=3.4 or dev-master will allow updates to any future version of the dependency. This includes major versions breaking backward compatibility.

Once a release of your package is tagged, you cannot tweak its dependencies anymore in case a dependency breaks BC - you have to do a new release but the previous one stays broken.

The only good alternative is to define an upper bound on your constraints, which you can increase in a new release after testing that your package is compatible with the new major version of your dependency.

For example instead of using >=3.4 you should use ~3.4 which allows all versions up to 3.999 but does not include 4.0 and above. The ~ operator works very well with libraries following semantic versioning.

Note: As a package maintainer, you can make the life of your users easier by providing an alias version for your development branch to allow it to match bound constraints.

-----

What are the options for "kodeine/laravel-acl": "dev-master"? Want to the the blade extensions.

**Comment by GESUMAYOR** [comment]
I solved the problem by cloning the master branch and replace with with the content of the laravel-acl folder in my vendor folder with the master on clone. It work very great and I had no need to do all my roles and permissions to give what views I needed based on the role
